### ISSUE TITLE
OSC: Add Int parameter for currently focused window

### ISSUE THREAD

**Issue by walllable** [Curtis-VL/OVRToolkit-Issues#102]
My current setup is that I have a plane with a screenshot of my monitor on it attached to my hand when `ToggleWindows` is set to `true`. I want to be able to change the image on it depending on which application on my desktop is focused (eg, show discord when Discord's focused, show Firefox when Firefox is focused, etcetc.) I'm not sure how you'd set which application corresponds to each number though... Maybe a config file or a settings screen of some sort?

**Comment by Curtis-VL** [comment]
I think for now at least this may be a bit outside of the scope! It would be cool for sure though!
