### ISSUE TITLE
F11 and F12 give odd names/values in bindings (Macros/Sim Mode)

### ISSUE THREAD

**Issue by nullstalgia** [Curtis-VL/OVRToolkit-Issues#118]
F11 shows up as:

![image](https://user-images.githubusercontent.com/20761757/156902165-d8e18436-8c9f-4452-8954-2f50e774824b.png)

![image](https://user-images.githubusercontent.com/20761757/156902123-34868f7f-7860-458a-8d36-da7f022464d2.png)

F12 shows up as:

![image](https://user-images.githubusercontent.com/20761757/156902145-daf47b11-e1a2-4322-b168-a4a9619080d5.png)

![image](https://user-images.githubusercontent.com/20761757/156902155-92545c11-da11-47c9-a23d-4017d39bb8b1.png)

**Comment by Curtis-VL** [comment]
Corrected, thanks!
