### ISSUE TITLE
F13-F24 aren't bindable with Macros or Sim Mode bindings

### ISSUE THREAD

**Issue by nullstalgia** [Curtis-VL/OVRToolkit-Issues#119]
Bit of a niche thing, but would be nice to use dedicated buttons for those things :o

**Comment by Curtis-VL** [comment]
I'm afraid this is just a limitation of the API! Right now it can only detect physical button presses, not simulated ones. :)

I'll keep it in mind but close this for now.

**Comment by nullstalgia** [comment]
Simulated? I'm pressing it on a keyboard that is sending a USB Keyboard signal?

**Comment by Curtis-VL** [comment]
There's a keyboard with keys over F12 without using macros...?

**Comment by nullstalgia** [comment]
Yes, I made one and you can buy them from other manufacturers. For example, Apples magic keyboard goes up past F12.

![Screenshot_20220306-124507_Firefox.jpg](https://user-images.githubusercontent.com/20761757/156941467-8dcb7678-57cc-40ea-b38c-14e650a10924.jpg)

**Comment by Curtis-VL** [comment]
Interesting! I'll send you some stuff in Discord so we can diagnose this.
