### ISSUE TITLE
Overhaul some macro creation/saving/loading logic

### ISSUE THREAD

**Issue by Curtis-VL** [Curtis-VL/OVRToolkit-Issues#122]
- [x] Change to saving macros in their own JSON files to allow for less jank saving.
- [ ] Change binding to 'whatever keys are pressed until all are released' is the bound keys.
- [x] Icons shouldn't need to be named numerically, save icon path versus icon index.
- [x] Add a 'Saved' message when clicking 'Save changed' on the macro editor.

(Ideally wanna get this done tomorrow as it's now blocking release!)

**Comment by nullstalgia** [comment]
- [ ] Add readme.txt in MacroIcons folder (mention the filetype and ideal size.)
- [ ] Add mention of MacroIcons folder to ConfigApp
- [ ] Add cancel button to icon selection

**Comment by Curtis-VL** [comment]
Improved binding of macros may be added at a later date, but the rest is done.
