### ISSUE TITLE
Additional Macro Polish

### ISSUE THREAD

**Issue by nullstalgia** [Curtis-VL/OVRToolkit-Issues#124]
- [x] Add readme.txt in MacroIcons folder (mention the filetype and ideal size.)
- [x] Add mention of MacroIcons folder to ConfigApp (Button to open the folder would be A+)
- [x] Add cancel button to icon selection
- [ ] Analytics (same as Sim Mode?)

**Comment by Curtis-VL** [comment]
Done!
