### ISSUE TITLE
Desktop captures always open with the missing process placeholder, must be manually recreated

### ISSUE THREAD

**Issue by EtiTheSpirit** [Curtis-VL/OVRToolkit-Issues#146]
This issue is really strange as it is very inconsistent. I have a layout where I have multiple monitors in my overlay.

When I start OVR Toolkit, my desktop capture windows have the placeholder that occurs when the overlay is unable to find a process, despite it being a desktop capture. The window title shows as "scord" and the process name is null.

To make matters even more weird, *sometimes* (about 40% of the time) clicking on my saved profile will fix it and show the desktops. It's hit or miss and fails more often than not, making it so I have to manually set the windows back to their respective monitors. I have a 3 monitor setup, not including the HMD's display.

To show off what I mean, I recorded a video of me starting SteamVR and trying to view my overlay. The window capture of Discord works great, but the desktop captures are broken as seen here: https://youtu.be/JhqsHQC7lMk - in this video, clicking on my profile did not fix it. After I stopped recording I tried to click my profile a few more times, clicked the Search button on one of the overlay windows as well. I ended up recording this twice but scrapped the first recording which was much shorter, so my previous log should be roughly the same thing.

Logs here:
[Player.log](https://github.com/Curtis-VL/OVRToolkit-Issues/files/10066421/Player.log)
[Player.Last.log](https://github.com/Curtis-VL/OVRToolkit-Issues/files/10066422/Player.Last.log)

Here's the json files for my layout (n.b. I renamed them to .txt so I could upload since GitHub doesn't like attached json files for some reason, they are still json files in the data folder of course).

SavedWindows\Preset1 (the Discord window attached to my left hand):
[window970.txt](https://github.com/Curtis-VL/OVRToolkit-Issues/files/10066501/window970.txt)

GlobalWindows (the three desktops):
[window2313.txt](https://github.com/Curtis-VL/OVRToolkit-Issues/files/10066502/window2313.txt)
[window9241.txt](https://github.com/Curtis-VL/OVRToolkit-Issues/files/10066503/window9241.txt)
[window9983.txt](https://github.com/Curtis-VL/OVRToolkit-Issues/files/10066504/window9983.txt)

**Comment by Curtis-VL** [comment]
I'll look into this. I've heard about it before.

Realistically, in no situation should a desktop capture ever show the 'Window not found' error. Should default to any desktop if it can't find the specified one!

**Comment by EtiTheSpirit** [comment]
I did some tinkering with the json files, I was able to fix it myself by manually setting type=0 and the title to `\\\\.\\DISPLAY#`

As far as what might have made it happen I honestly don't know since it was some time ago, I believe I was tinkering with the profile system for the first time (hence why only one of the four windows is there in a profile).

**Comment by Curtis-VL** [comment]
Type was set to 1!?

**Comment by Curtis-VL** [comment]
Okay! I've made some quick changes to this. In theory... So long as the object for the desktop capture is active, it will actually save as a desktop capture now. (I know this sounds stupid, but it is in theory a fix)

I'll close this for now, but please do let me know if the issue crops up again after the next public release on Monday! Feel free to re-open this if so!
