### ISSUE TITLE
[Feature Request] Auto update VRChat chatbox

### ISSUE THREAD

**Issue by DingBoy01** [Curtis-VL/OVRToolkit-Issues#152]
It would be cool if whenever you were typing in the new textbox linked to VRC, it would auto update you typing and people could see you typing live. Then you could change the send button/enter to clear the textbox.

There is a separate program that does this but it would be cool if Toolkit had this integrated so you don't need extra programs running.

**Comment by DingBoy01** [comment]
Obviously, you would set this as a toggle in the settings. So you can turn it off and on.

**Comment by TayouVR** [comment]
that would be cool, yeah

**Comment by Curtis-VL** [comment]
Just a note but it does show the 'typing' icon now as of an open beta from a few days ago! Just waiting for Monday to release these changes. :)

**Comment by ThizThizzyDizzy** [comment]
the chatbox also has a notification sound, so constant updates would not be a good thing

**Comment by Curtis-VL** [comment]
Yeahhhhh, the notification sound sucks when people use those applications that show music playing with the timestamp that gets updated. :(

**Comment by DingBoy01** [comment]
Thank you for adding this in the recent update!
