### ISSUE TITLE
Find out why 2 clicks is always required to interact with an overlay

### ISSUE THREAD

**Issue by Curtis-VL** [Curtis-VL/OVRToolkit-Issues#3]
Find out why 2 clicks is always required to interact with an overlay.

**Comment by nullstalgia** [comment]
For me, this doesn't seem to happen during normal operation. (But Lev and Curtis said this happens for them near always)

But I can reproduce it reliably when:

1. Enable Edit Mode
2. Open a window's settings
3. DO NOT GO TO "Home," close Edit Mode but leave windows toggled
4. Overlays now need to be clicked twice until you go "Home"

**Comment by fwenny** [comment]
For me it is also a 100% reproducible:
Open overlay with binding
Put cursor on window
1st click is always ignore

Additionally, if I move the cursor out of the window, it causes the cursor to jump to the top left corner.
If I then bring the cursor back and try clicking, 1st click is again ignored.

This is also additionally to the issue where sometimes despite me clicking trigger (left click), the right click is being registered.

**Comment by Curtis-VL** [comment]
Thanks for the input! I'll be looking into this as soon as I've finished work on #49!

**Comment by Curtis-VL** [comment]
> For me it is also a 100% reproducible: Open overlay with binding Put cursor on window 1st click is always ignore
> 
> Additionally, if I move the cursor out of the window, it causes the cursor to jump to the top left corner. If I then bring the cursor back and try clicking, 1st click is again ignored.
> 
> This is also additionally to the issue where sometimes despite me clicking trigger (left click), the right click is being registered.

For this, do you have the keyboard open maybe? This is intended behaviour if the keyboard is open to avoid accidentally hovering over another window causing loss of input to a text field.
With the keyboard closed, just hovering over another window should bring it into focus and an initial click through go through.

I'm having a little trouble reproducing this issue.

**Comment by Curtis-VL** [comment]
> For me, this doesn't seem to happen during normal operation. (But Lev and Curtis said this happens for them near always)
> 
> But I can reproduce it reliably when:
> 
> 1. Enable Edit Mode
> 2. Open a window's settings
> 3. DO NOT GO TO "Home," close Edit Mode but leave windows toggled
> 4. Overlays now need to be clicked twice until you go "Home"

I thought I could reliably reproduce it, but I actually just had the keyboard open, with it closed all works as intended. (The initial click is by design when the keyboard is open to avoid accidentally taking input fields out of focus when hovering over another overlay)

However, I have fixed the Window Settings issue you mentioned!

**Comment by fwenny** [comment]
so, two things:
most people will have the keyboard open, and it will rarely be somewhere where accidental clicks would happen. please consider changing it as it is very frustrating..
second thing, even with keyboard closed first click is ignored.

**Comment by Curtis-VL** [comment]
> so, two things: most people will have the keyboard open, and it will rarely be somewhere where accidental clicks would happen. please consider changing it as it is very frustrating.. second thing, even with keyboard closed first click is ignored.

I promise it's MUCH more frustrating without the initial click requirement if the keyboard is open! That's why it was added. :)

Lets say you open the keyboard, then click on a text field in Discord to type in. As you move your cursor down to the keyboard it brushes by another window, now you need to select the text field again. As you go to move back to the keyboard, you hit the same window again, text field is out of focus again. Rinse, repeat. (I was going insane with this!)

Maybe it could be optional though for sure.

For the second issue, I can't reproduce this. With the keyboard closed and Window Settings closed regardless of if Edit Mode is open or not (Per my comment about about fixing an issue there), it seems to work as intended for me. I might need some help there!

**Comment by fwenny** [comment]
I might misunderstood. Is it not possible, with a single click, to both focus on the window and also initiate a click?
I agree that brushing the cursor over another window, and that causing it to get focus will be annoying.
I didnt think it worked like that though. Only when you click it should switch focus and also click.

How can I help with the other issue? Ill try again but Im almost certain it is always the case for me.

**Comment by Levtastic** [comment]
I think I've had the two clicks problem without a keybord or window settings open - I have 6 overlays, 4 of which are windows that on the actual desktop are partially overlapping each other, *and* often behind the game preview window - I had assumed that the different layers being complicated was the reason for needing two clicks, in case that helps you diagnose what's up.

**Comment by nullstalgia** [comment]
Note from someone with a specific usecase:

I never use the per-window capture due to it resizing my windows and unmaximizing them, etc. So I currently *purely* use the Desktop capture. 

So the extra tap needed to focus the overlay would not be beneficial for my usecase.

Maybe that's why I'm not experiencing the issue? I think I also have the option to automatically tab into hovered-over windows disabled.

**Comment by Curtis-VL** [comment]
> I might misunderstood. Is it not possible, with a single click, to both focus on the window and also initiate a click? I agree that brushing the cursor over another window, and that causing it to get focus will be annoying. I didnt think it worked like that though. Only when you click it should switch focus and also click.
> 
> How can I help with the other issue? Ill try again but Im almost certain it is always the case for me. edit: I only use 1 window, but I can try adding a second one, because Im almost certain hovering over the window, with the keyboard closed or open, does NOT switch focus.

I mean, now that you mention it... This really is how it should work. Click should bring the window into focus and hold the click until the window is in the foreground.

I believe I have it as I do so that the window has time to get into the foreground before your click, otherwise anything overlapping it may be clicked on instead.

**Comment by fwenny** [comment]
I tested this with two separate windows.
With or without the keyboard the behavior is the same: Hovering over the window does nothing, and first click is ignored.

If I setup so one window is in-front of the other, clicking the foreground window does nothing (first click ignored), however if I then move the cursor to the background window, first click is registered.

Its as if clicking on a OVR Toolkit "wakes it up" so you can interact with them, and the moment your cursor moves out of the window bounds its:
1. "goes to sleep" again (first click will get ignored)
2. cursor jumps to the top left corner

**Comment by Curtis-VL** [comment]
> Note from someone with a specific usecase (me):
> 
> I never use the per-window capture due to it resizing my windows and unmaximizing them, etc. So I currently _purely_ use the Desktop capture.
> 
> So the extra tap needed to focus the overlay would not be beneficial for my usecase.
> 
> Maybe that's why I'm not experiencing the issue? I think I also have the option to automatically tab into hovered-over windows disabled.

You get this issue with a monitor capture...? Now that shouldn't be possible.

**Comment by Curtis-VL** [comment]
> I tested this with two separate windows. With or without the keyboard the behavior is the same: Hovering over the window does nothing, and first click is ignored.
> 
> If I setup so one window is in-front of the other, clicking the foreground window does nothing (first click ignored), however if I then move the cursor to the background window, first click is registered.
> 
> Its as if clicking on a OVR Toolkit window "wakes it up" so you can interact with them, and the moment your cursor moves out of the window bounds its:
> 
> 1. "goes to sleep" again (first click will get ignored)
> 2. cursor jumps to the top left corner

Are you in Edit Mode? Or have your windows pinned and have Edit Mode off?

**Comment by fwenny** [comment]
I was not in edit mode.
The windows were not pinned.

**Comment by Curtis-VL** [comment]
Clearly I'm missing something. I'll see if I can figure it out with some others in Discord maybe. :)

**Comment by nullstalgia** [comment]
> You get this issue with a monitor capture...? Now that shouldn't be possible.

Ah, you misinterpreted what I said, probably my fault for not clarifying in that message too. I *don't* have this issue, and I was explaining why I think I don't get it (plus some other opinions).

Sorry if I spooked you 😅

**Comment by Curtis-VL** [comment]
> 

AH, right! That's fine! De-spooked! :)

**Comment by fwenny** [comment]
do you have any kind of ETA on a fix for this?

**Comment by Curtis-VL** [comment]
Now that I'm done with keyboard stuff until I start the keyboard word suggestions overhaul, I can have a look into this tomorrow!

However, I've had issues reproducing it in the past. On my side it seems to work as intended, with a click only being required if the keyboard is open.

**Comment by fwenny** [comment]
what kind of settings would be relevant? 
and also, would you be able to simply add a toggle to disable the required click, with or without the keyboard as a workaround for now? i really dont see the need for it.

**Comment by Curtis-VL** [comment]
The reason it's enabled is so that hovering over other overlays doesn't tab out the program you're trying to type on, it was a very common problem early days before that feature was implemented.

Either way, I don't believe this issue is specific to that is it? I thought you could reproduce it with the keyboard closed? :o

Of course I can add a toggle still though.

**Comment by fwenny** [comment]
the click gets ignored with or without the keyboard.
hovering over other windows does nothing to the focus of the window.

**Comment by Curtis-VL** [comment]
I've just had a quick look into some of the conditions that must be met to allow it to automatically tab in without a click and one of them looks to have a typo. It seems like it was in place to take into account that the keyboard can still be 'open', even though it's not currently visible because it's open in edit mode only for example.

So, I've removed this condition and made the keyboard open detection more robust.

If you could, please give the Closed Beta branch a try and let me know if that helped at all!
The beta code is:
reportissuesindiscord

**Comment by fwenny** [comment]
unfortunately this did nothing for me.
ive tried using the window, with or without keyboard, in edit mode (clicking the gear icon) and outside edit mode, the behavior is the same, first click gets ignored (and cursor jumps to the top left corner of the screen when mouse leaves window area)

**Comment by Curtis-VL** [comment]
And you're sure 'Alt tab into windows' or whatever on the window outside of VR is enabled? :o

**Comment by fwenny** [comment]
to be fair, ive only seen the desktop Settings window only once, and ive never fiddled with the options.
i see there are 3 tab options:
alt tab on changing windows
automatically alt tab into games
tab out on window toggle

i have all of them disabled, and i have no idea what they actually do.  should i enable them?

**Comment by Curtis-VL** [comment]
Ahhh, yes, you actually have click to focus enabled then. :)

Enable all settings except the 2 bottom ones, this is the default.

**Comment by fwenny** [comment]
so all along it was an option i somehow disabled? welp lol.
i have only enabled the first one, alt tab on changing windows, and now with or without the keyboard, first click is registered. 
i dont know if thats how its intended to work, but im happy (im back on release branch if that helps). thank you very much.

i do wonder if you could write a short explanation about what each of the 3 alt tab options do? i dont remember seeing it anywhere.

anyway, thanks again.

**Comment by Curtis-VL** [comment]
For sure, planned! Needs tool tips badly.

I'll close the issue for now and implement some tool tips when I get time!
