### ISSUE TITLE
Add Issue Tracker and related Discord Server links to OVRT Bot commands

### ISSUE THREAD

**Issue by nullstalgia** [Curtis-VL/OVRToolkit-Issues#50]
`!issue` / `!issues` for this issue tracker

`!vd` for the Virtual Desktop Discord -> https://discord.com/invite/74y7a6w

`!ovras` for the OVR Advanced Settings Discord -> https://discordapp.com/invite/cW6cRyv

**Comment by Curtis-VL** [comment]
Added, just waiting for server tech to reboot the bot.
