### ISSUE TITLE
Window names do not match between set contents and window list

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [Curtis-VL/OVRToolkit-Issues#56]
The names for Windows in the set contents menu do not match the names shown in the window list
my desktops \\.\DISPLAY1 and \\.\DISPLAY2 show as Desktop 1 and Desktop 0 respectively
cameras all show as Unknown in the window list
The chrome window shows the current tab name under set contents, but the first tab's name in the window list

I realize the specific differences here are likely due to different APIs returning different names, but it would be good to use the same name in both places

note: desktops 1 & 2 being in reverse order is likely due to me using my second monitor as my main display

**Comment by Curtis-VL** [comment]
Fixed, thanks!
