### ISSUE TITLE
[Feature Request] Secondary Low Battery Notification When at 10m Remaning

### ISSUE THREAD

**Issue by TheLastRar** [Curtis-VL/OVRToolkit-Issues#59]
I would like a second distinct alert for when the trackers have 10m of battery left

Optionally, if you want to go the extra mile you could provide us the ability to set what percentage/time the battery alerts go off, rather than having it hardcoded.

**Comment by Curtis-VL** [comment]
This is a good idea!

**Comment by Curtis-VL** [comment]
Implemented internally, will be in next week's release. Thanks for the suggestion!
