### ISSUE TITLE
Fix wiki page for SteamVR Autostart

### ISSUE THREAD

**Issue by TayouVR** [Curtis-VL/OVRToolkit-Issues#68]
The wiki page for steamVR autostart currently states incomplete and misleading information:
> **Launch OVR Toolkit with SteamVR automatically**
> 
> Follow these instructions to set OVR Toolkit to launch automatically with SteamVR:
> 
> - Start SteamVR.
> - Access the SteamVR Settings menu. **_(Outside of VR)_**
> - Go to the 'Startup/Shutdown' tab.
> - Find 'OVR Toolkit' in the list. _**(The first entry, there may be others further in the list which should be left as autorun 'off'!)**_
> - Select the 'On' for the slider next to 'OVR Toolkit'.
> 
> To stop OVR Toolkit launching with SteamVR, turn off this slider.

it should instead say:
> **Launch OVR Toolkit automatically with SteamVR**
> 
> Follow these instructions to set OVR Toolkit to launch automatically with SteamVR:
> 
> - Start SteamVR.
> - Access the SteamVR Settings menu. **(available in the dashboard and in the desktop window)**
> - Go to the 'Startup/Shutdown' tab.
> - Find 'OVR Toolkit' in the list. 
> - Select the 'On' for the slider next to 'OVR Toolkit'.
> 
> To stop OVR Toolkit launching with SteamVR, turn off this slider.

**Comment by Curtis-VL** [comment]
Fixed. I've not really seen the issue that caused it to be worded like that for a long time, maybe it was fixed?

**Comment by TayouVR** [comment]
You removed the notice about disabling anything else, but you still direct people to the settings outside of VR even though the window is available both in **AND** outside. 

And to add to this from the discord chat (https://discord.com/channels/491621961370304513/594370309591793725/934862370562539531) rephrasing it to `Go to 'Choose Startup Overlay Apps'` and `Select 'On' for the slider next to OVR Toolkit` instead of the Find it and Select lines

**Comment by Curtis-VL** [comment]
Note that a lot of people don't know what the 'dashboard' is! I don't think it's wise to use that wording, probably just say the 'settings in VR' for example instead.

**Comment by TayouVR** [comment]
> Note that a lot of people don't know what the 'dashboard' is! I don't think it's wise to use that wording, probably just say the 'settings in VR' for example instead.

I have changed my comment with a better description ^^

**Comment by Curtis-VL** [comment]
Fixed.
