### ISSUE TITLE
Feature request: Comfort features for permanent "edit mode" users

### ISSUE THREAD

**Issue by wilk-polarny** [Curtis-VL/OVRToolkit-Issues#73]
Hi,

I would like to suggest the following features:

Since I mostly work in edit mode (double squeezing controllers to hide/display all windows and the keyboard), I thought it would be nice to:

- Have the keyboard optionally (re-) respawn each time edit mode is entered
--> For the above use case, this would not require closing the keyboard and opening it again (useful when the keyboard is left on a different end of the play space)

- Allow for all elements to be placed freely as is, but have them (optionally) respawn relative to the HMD position+rotation
--> Spawn windows within the room, exit edit mode --> move physically within the playspace --> have the windows respawn at the same position relative to the user - so they windows don't follow the HMD permanently, but will reposition once they are called in again using the squeeze gesture.
The only alternative now is to drag windows along or go through the menu and have them (re-) spawn in front of me

- It would be nice to have all elements move with the play space (when the place space is for example manipulated using OVR Advanced Settings)

I don't even know whether the workflow (Single desktop window + keyboard only and hide/show with edit mode / squeeze gesture) I'm using is common at all or whether I'm using OVR Toolkit in an unintended way. These are just ideas how to increase comfort in my specific scenario - where I have to drag along windows/keyboards each time I move across the room (I sit or lay down a lot, move through the apartment to sit on an office chair, move on to my dining table, etc.).

Would anything mentioned make any sense for a broader range of users?

**Comment by Curtis-VL** [comment]
Hi there!

I think with all of these you may be looking for the 'Recenter window' option in Window Settings?

This will save your windows relative to your HMD position when you toggled them on, this way if you place a window in front of you, turn around, toggle them off and back on, they'll appear in front of you again. The keyboard will follow this same logic if any window has the setting enabled. :)

For playspace moving, just toggle the windows off and back on and they'll be back in front of you again after moving. (Using double grip)

**Comment by wilk-polarny** [comment]
Wait, it's already implemented? Kinda went unnoticed by me. If that's the case, thanks! I'll give it a try!

**Comment by Curtis-VL** [comment]
> Wait, it's already implemented? Kinda went unnoticed by me. If that's the case, thanks! I'll give it a try!

If it doesn't do what you're hoping let me know! Just post a new comment in here and I'll re-open the issue. :)

**Comment by nullstalgia** [comment]
@wilk-polarny Here's a video showing off Recenter Windows!

https://streamable.com/fvyl9f

**Comment by wilk-polarny** [comment]
Thank you, @Curtis-VL and @nullstalgia - I found the option and it seems to work as described! The only thing I noticed is that it won't adjust with a different pitch of the HMD, though - which I guess is some intentional limitation?

For example, If I were to sit or lay down and look up / down, the height adjustment and pitch of the windows/keyboard will not adjust - instead the windows will move to a point above or below my gaze direction - right to the point where they would tilt if I were to drag them (up or down) manually.

Is there a way to remove this constraint to allow for more or less the same keyboard - but a more comfortable window position?

I tried to sketch what I mean - the red block represents the actual window position, the green represents my expected position when facing "up" with the HMD

![telegram-cloud-document-4-6014603413122189793](https://user-images.githubusercontent.com/819238/150912744-c5bed855-642e-473f-999e-0186c189e7c0.jpg)

**Comment by Curtis-VL** [comment]
Yep, intentional limitation!

Curved SteamVR overlays become 'cones' when they're off-axis.

If you open the SteamVR Dashboard and look at the curved overlay that is  the bottom bar with buttons on it, notice how the upper left and right corners are further outwards than the lower bottom left/right corners. Unfortunately, Valve didn't make this a toggle.

As a result, I have to force overlays to be upright really, or, not curved when not upright. I think for the recentering function it would be a bit weird if it took all your windows out of curve to make them to certain places, so I opted to have it like it is now. :)

**Comment by nullstalgia** [comment]
> I think for the recentering function it would be a bit weird if it took all your windows out of curve to make them to certain places

I think this would be acceptable as an optional thing in Global Settings. "Allow rotating pitch when recentering" and it has a popup "Warning: This will undo your curve if the pitch changes!" (or similar)
