### ISSUE TITLE
Media controls

### ISSUE THREAD

**Issue by fwenny** [Curtis-VL/OVRToolkit-Issues#78]
Hiya, a smol bug appeared in the latest version.
The wirstwatch has the media controls addon you can add, but even when it is removed, next time ovr toolkit is launched it is there again.
I have to go to wirstwatch modules > add media control > remove media control to fix it.

**Comment by walllable** [comment]
I've encountered this as well

**Comment by Curtis-VL** [comment]
Thanks for the report, investigating.

**Comment by Curtis-VL** [comment]
Fixed in the update on 31/01/2022.
