### ISSUE TITLE
OVR Toolkit breaks if vrcompositor crashes

### ISSUE THREAD

**Issue by fwenny** [Curtis-VL/OVRToolkit-Issues#80]
Hi. There is an annoying issue with OVR Toolkit regarding crashing of SteamVR compositor.

Sometimes during gameplay my compositor would crash. I can then restart the compositor to keep playing, however ovr toolkit automatically closes.

Upon reopening of OVR Toolkit, I do not have access to the wristwatch anymore (so I cannot open keyboard anymore). I can only see the windows I had.
I have to restart SteamVR to fix it.

Anything you can do?

**Comment by Curtis-VL** [comment]
Hi there!

I'd suggest fixing SteamVR as this is intended behaviour on OVR Toolkit's side. If the compositor closes then its access to overlays is lost and it cannot create them anymore. :o

The better question is why is SteamVR crashing I suppose. If you'd like to join us on Discord I can have a look at your SteamVR logs if you'd like!

**Comment by fwenny** [comment]
My compositor crashes sometimes when Im in a VR game, though not often. I was hoping theres something you can do on your side as it sucks to not have a keyboard, but I understand if its not something you want to mess with.

**Comment by Curtis-VL** [comment]
It's possible there is something I could do, but I think fixing SteamVR would be the easiest solution. This doesn't affect anyone else I believe. :)

Like I said, if you'd like feel free to hop in our Discord and I can see if I can find the cause of the issue on SteamVR's side for you. Generally speaking, compositor crashes are related to GPU drivers, make sure you're on the latest GPU drivers and latest version of Windows!
