### ISSUE TITLE
Potential Wiki Entry: Blacklisting OVR Toolkit Settings app from NVIDIA's Overlay/Shadowplay

### ISSUE THREAD

**Issue by nullstalgia** [Curtis-VL/OVRToolkit-Issues#84]
So this is an issue I dealt with for a long time, but luckily I found a fix, and maybe it would be worth putting it on the wiki.

Issue: Starting OVR Toolkit while you have the NVIDIA Overlay enabled, causes the overlay to often become attached to the OVRT Settings app, rather than the VR game at hand. This often occurs due to the settings app *requiring* focus momentarily, and in that period NVIDIA's overlay will often attach itself. (I understand the focus is required, just wanted to mention it.) So if I wanted to Shadowplay the game I'm playing, I'd have to turn off OVRT Autostarting/Close it until I open the game.

Solution: Unfortunately, there is no official way for a user to add an executable to the blacklist NVIDIA uses for the Overlay. We *can* request to be added via *some* contact somewhere, but I doubt anything would come of that in a timely fashion. So, what we can do is add a profile to our PC's NVIDIA Settings and mark it with a tag that says we don't want the overlay on this. With the open-source app [NVIDIA Profile Extender](https://github.com/Orbmu2k/nvidiaProfileInspector) we can do both of those. 

Open it, it will ask for Admin permissions. Click this button to add a new profile, name it something related like OVR Toolkit. 

![image](https://user-images.githubusercontent.com/20761757/153784814-d4591cf1-f1f9-4bfa-83c5-82f9e840c4d5.png)

Click this button to add the OVR Toolkit ConfigApp executable to the profile. For my PC, it was in: `"C:\Program Files (x86)\Steam\steamapps\common\OVR Toolkit\ConfigApp\OVR Toolkit Settings.exe"` If your OVRT install is in your C Drive, you can copy that.

![image](https://user-images.githubusercontent.com/20761757/153784844-84a5b60f-7018-4da1-b05b-5bcf60a0a2ef.png)

Click this button to toggle on the Unknown Settings (usually only NVIDIA-made profiles have these values set).

![image](https://user-images.githubusercontent.com/20761757/153784933-b38de2e1-94ee-4a29-9048-15a569cd5ccd.png)

Scroll *all* the way down, into the Unknown section, until you find the address on the left: 0x809D5F60. On the right side you'll see the current value. Open the dropdown in the middle and select the value: `0x10000000` .

![image](https://user-images.githubusercontent.com/20761757/153785234-4e9d7a03-234d-476e-9528-8cdefcae4b1d.png)

Now hit "Apply changes," and you're set! No more OVR Toolkit stealing the overlay!

![image](https://user-images.githubusercontent.com/20761757/153785428-b7dcb918-b91d-4b76-bc09-0ca57661bf89.png)

**Comment by Curtis-VL** [comment]
I've linked to this issue on the wiki as that's easier than reflecting the instructions with images on there. Thanks! :)
