### ISSUE TITLE
Send OSC message to VRChat when toggling keyboard

### ISSUE THREAD

**Issue by walllable** [Curtis-VL/OVRToolkit-Issues#90]
Similar to how you currently have it set up for window toggles and edit mode, but for the keyboard instead.

**Comment by Curtis-VL** [comment]
Good idea!

**Comment by Curtis-VL** [comment]
Added!

Parameter will be 'ToggleKeyboard', also modified 'EditMode' to 'ToggleEditMode' for consistency.
