### ISSUE TITLE
Export current window layout/dimensions to Unity Prefab file for use in other games

### ISSUE THREAD

**Issue by walllable** [Curtis-VL/OVRToolkit-Issues#91]
I'm mostly making this feature request so that when I set up my VRC avatar for OVRT's OSC support, I can have planes appear in roughly the same place in VRChat as they do in OVRT. An obvious use for this is to show (roughly at least, if you set it up right) your OVRT window layout in VRC when you toggle windows.

**Comment by Curtis-VL** [comment]
I think though this is a cool idea, it may not be totally possible! For example, curved overlays are an unknown! For now at least, I'll close this, but I'll keep it in mind as a possible future feature!
