### ISSUE TITLE
Send OSC message to VRChat when a particular window is unhidden because of gaze

### ISSUE THREAD

**Issue by walllable** [Curtis-VL/OVRToolkit-Issues#92]
Maybe this is a bit of a scope creep sorta thing? But I have a couple windows that I usually keep hidden unless I look at them, and it'd be neat to show in VRChat whether I'm looking at that particular window or not. I dunno how you'd show that you're looking at a specific window though... Maybe this could be easier if it's just a global "Looking at any unhidden window" sorta thing?

**Comment by Curtis-VL** [comment]
Ahh, might be scope creep for now! We'll just see if anyone uses the current implementation first, then maybe move on to cooler stuff like that. :)
